### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by jw-97** [nomadcoders/noom#2]
#0.2 Server Setup (07:17)

환경은 window 입니다.

npm run dev  실행시 

-------------------------------------------------------------------------------------------------------------------------------------

(node:1288) Warning: To load an ES module, set "type": "module" in the 
package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)D:\nomad\zoom\src\server.js:1
import express from "express";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)      
    at Module._compile (C:\Users\82103\AppData\Roaming\npm\node_modules\@babel\node\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (C:\Users\82103\AppData\Roaming\npm\node_modules\@babel\node\node_modules\pirates\lib\index.js:104:7)        
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) 
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at Object.<anonymous> (C:\Users\82103\AppData\Roaming\npm\node_modules\@babel\node\lib\_babel-node.js:176:21)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by jw-97** [comment]
package.json 최상단에
"type": "module",
을 추가함으로써 해결 되었습니다 !!
